### PR TITLE
Fix error when restoring ExternalName services

### LINKED ISSUE #786: ExternalName service restores log errors saying "key ports not found"
**What steps did you take and what happened:**
[A clear and concise description of what the bug is, and what commands you ran.)

Backup and restore an ExternalName service (https://kubernetes.io/docs/concepts/services-networking/service/#externalname)

The services restore properly, but the restore results show an error saying `key ports not found`

**What did you expect to happen:**

There shouldn't be any errors in the restore results.

This is caused by the restore service action which clears out auto-assigned NodePort values from service ports.  It returns an error if `.spec.ports` isn't found.  Should be updated to not error here, at least for `ExternalName` services.

### PR DESCRIPTION
**Pull request by shubheksha**
Fixes #786

### CODE REVIEW

**Comment by shubheksha** [comment]
Made changes based on the discussion with @carlisia on Slack.
Not sure if this is the correct approach - how do we identify if a service is of type ExternalName?
I'd appreciate some direction here :)

File: pkg/restore/service_action.go [hunk 1]
```diff
@@ -57,6 +57,11 @@ func (a *serviceAction) Execute(obj runtime.Unstructured, restore *api.Restore)
 		delete(spec, "clusterIP")
 	}
 
+	// Since spec.ports is an optional key, we can ignore 'not found' errors. Also assuming it was a string already.
+	if val, _ := collections.GetString(spec, "spec.ports"); val != "None" {
+		delete(spec, "spec.ports")
```
Comment (ncdc) [inline pkg/restore/service_action.go]: I don't think we want to delete `spec.ports`; instead, down below where we access `spec.ports`, we want to be ok with the field not being there for `spec.type == ExternalName` services.

Comment (shubheksha) [reply pkg/restore/service_action.go]: Ah, ok! Makes sense 👍

**Comment by ncdc** [comment]
I think it might make the code more readable if we had a separate function for dealing with nodePorts (essentially all of https://github.com/heptio/ark/blob/a28327b47e80dcd4f393c0eba942c741280925db/pkg/restore/service_action.go#L60-L103). We could then either have it no-op if type=ExternalName, or do the type check first, and only call the separate function if type != ExternalName.

@carlisia how's that sound to you?

**Comment by carlisia** [comment]
@ncdc I really like this. This piece of code is obscure enough that branching out and not having to look at it unless you need to in this case makes the code as a whole more readable. I also particularly like the no-op alternative.

**Comment by nrb** [comment]
Thanks for the PR @shubheksha!

File: pkg/restore/service_action.go [hunk 2]
```diff
@@ -57,28 +57,10 @@ func (a *serviceAction) Execute(obj runtime.Unstructured, restore *api.Restore)
 		delete(spec, "clusterIP")
 	}
 
-	preservedPorts, err := getPreservedPorts(obj)
-	if err != nil {
-		return nil, nil, err
-	}
-
-	ports, err := collections.GetSlice(obj.UnstructuredContent(), "spec.ports")
+	err = deleteNodePorts(obj, &spec)
```
Comment (ncdc) [inline pkg/restore/service_action.go]: I know we just merged this, but:
`if err := ...; err != nil {`

File: pkg/restore/service_action.go [hunk 3]
```diff
@@ -101,3 +83,29 @@ func getPreservedPorts(obj runtime.Unstructured) (map[string]bool, error) {
...
+
+func deleteNodePorts(obj runtime.Unstructured, spec *map[string]interface{}) error {
+	preservedPorts, err := getPreservedPorts(obj)
+	if err != nil {
+		return err
+	}
+
+	ports, err := collections.GetSlice(obj.UnstructuredContent(), "spec.ports")
+	serviceType, _ := collections.GetString(*spec, "type")
+	if err != nil && serviceType != "ExternalName" {
```
Comment (ncdc) [inline pkg/restore/service_action.go]: I think it would be clearer if we instead checked if the type is ExternalName up front, either at the top of this function (with an immediate `return nil`) or in the calling function (don't call this function if ExternalName).

Comment (carlisia) [reply pkg/restore/service_action.go]: I'm the one who opted for the alternative of a no-op but when I read it again I had the same thought. Apologies for misleading but this is a good minor change. I'll open a new tix.
