### PR TITLE
make PVProvider optional in server config; disallow snap/restore PVs …

### LINKED ISSUE #44: AWS compatible support no longer working
First off, thanks for the interesting project, appreciate the effort. I was walking through the tutorial for using Ark w/ Minio and a PV backup. 

I believe that commit #35 has broken support for AWS compatible services, such as Minio, as it is now attempting to actually validate the EC2 AZs and is using the `minio` region which does not exist.  

Looking into the code, the endpoint resolver is setup to deal with this for S3 however other services are explicitly not being supported. 

Steps to reproduce: 
- Follow the examples with the Minio provider. 

Outcome: 
- Ark server errors with: 

```
caused by: Post https://ec2.minio.amazonaws.com/: dial tcp: lookup ec2.minio.amazonaws.com on 10.0.0.10:53: server misbehaving
```

### PR DESCRIPTION
**Pull request by skriss**
…when not provided

Fixes #44 

Signed-off-by: Steve Kriss <steve@heptio.com>

### CODE REVIEW

**Comment by skriss** [comment]
ref. https://github.com/heptio/ark/pull/35#discussion_r132951946

File: pkg/controller/gc_controller.go [hunk 1]
```diff
@@ -115,6 +115,12 @@ func (c *gcController) cleanBackups() {
 			}
 
 			for _, volumeBackup := range backup.Status.VolumeBackups {
+				if c.snapshotService == nil {
+					glog.Warningf("Cannot garbage-collect snapshot %s for backup %s/%s because server is not configured with PersistentVolumeProvider",
```
Comment (ncdc) [inline pkg/controller/gc_controller.go]: Copying my comment from the original PR:

> If the snapshot service is nil, the net result is that backups will be GC'd but associated snapshots will be orphaned?

Steve's reply:
> yes. it's a strange situation to be in - you created backups with snapshots, meaning you had a snapshotservice configured, but now you're in a mode where if you restore from them you won't use them. i suppose the alternative is to not GC any backups with snapshots in this scenario - WDYT?

Comment (ncdc) [inline pkg/controller/gc_controller.go]: I don't want to orphan data if we can avoid it

Comment (ncdc) [inline pkg/controller/gc_controller.go]: Let's put a check before the DeleteBackup call to see if the backup has any VolumeBackups. If it does and the snapshotService is nil, then log and skip deleting the backup.

**Comment by skriss** [comment]
@ncdc still need to test and update some of the examples to remove config that's no longer necessary, but you can take a look at the code now.

File: pkg/backup/volume_snapshot_action.go [hunk 2]
```diff
@@ -38,11 +39,15 @@ type volumeSnapshotAction struct {
 
 var _ Action = &volumeSnapshotAction{}
 
-func NewVolumeSnapshotAction(snapshotService cloudprovider.SnapshotService) Action {
+func NewVolumeSnapshotAction(snapshotService cloudprovider.SnapshotService) (Action, error) {
```
Comment (ncdc) [inline pkg/backup/volume_snapshot_action.go]: The more I think about it, I'm not sure that changing the signature here really provides much value?

File: pkg/controller/gc_controller.go [hunk 3]
```diff
@@ -108,26 +108,36 @@ func (c *gcController) cleanBackups() {
 	// storage should happen first because otherwise there's a possibility the backup sync
 	// controller would re-create the API object after deletion.
 	for _, backup := range backups {
-		if backup.Status.Expiration.Time.Before(now) {
-			glog.Infof("Removing backup %s/%s", backup.Namespace, backup.Name)
-			if err := c.backupService.DeleteBackup(c.bucket, backup.Name); err != nil {
-				glog.Errorf("error deleting backup %s/%s: %v", backup.Namespace, backup.Name, err)
-			}
+		if !backup.Status.Expiration.Time.Before(now) {
```
Comment (ncdc) [inline pkg/controller/gc_controller.go]: Do you think checking for "expiration after now" is clearer than "expiration not before now"?

Comment (skriss) [inline pkg/controller/gc_controller.go]: I had the same thought, decided it was tomayto-tomahto, but if switching it strikes you as more clear I can do that.

Comment (ncdc) [inline pkg/controller/gc_controller.go]: whatevs :)

File: pkg/backup/volume_snapshot_action.go (hunk 2 above)
Comment (skriss) [inline pkg/backup/volume_snapshot_action.go]: the intent was to embed the nil-checks into the library so if someone uses it outside the ark server they still get argument validation. what would you do differently? leave as it was?

Comment (ncdc) [inline pkg/backup/volume_snapshot_action.go]: I can see that... what I was thinking was "you're not going to call NewVolumeSnapshotAction if you don't have a snapshotService", but you never know what crazy things people will do 😄 . This is fine to keep.

**Comment by skriss** [comment]
@abiogenesis-now I decided it was most clear to break out the reference tables for config based on what it's being used for. PTAL.

**Comment by skriss** [comment]
I've tested these changes on all of the supported platforms

File: docs/config-definition.md [hunk 4]
```diff
@@ -25,17 +25,12 @@ metadata:
   name: default
 persistentVolumeProvider:
   aws:
-    region: minio
```
Comment (skriss) [inline docs/config-definition.md]: Note that I switched this example to AWS because minio PVProvider config is no longer required (or valid), and unfortunately we can't currently mix/match AWS PVProvider with minio backup storage provider due to the single source of credentials.

File: docs/config-definition.md [hunk 5]
```diff
@@ -63,22 +58,44 @@ The configurable parameters are as follows:
...
+| Key | Type | Default | Meaning |
+| --- | --- | --- | --- |
+| `region` | string | Required Field | *Example*: "us-east-1"<br><br>See [AWS documentation][3] for the full list. |
+| `availabilityZone` | string | Required Field | *Example*: "us-east-1a"<br><br>See [AWS documentation][4] for details. |
+
 ### GCP
+
+#### backupStorageProvider
+
+No parameters required; specify an empty object per [example file][13].
```
Comment (skriss) [inline docs/config-definition.md]: @ncdc @abiogenesis-now does this seem reasonable?

File: docs/config-definition.md (hunk 4 above)
Comment (abiogenesis-now) [inline docs/config-definition.md]: that makes sense

File: docs/config-definition.md [hunk 6]
```diff
@@ -63,22 +58,44 @@ The configurable parameters are as follows:
...
 
+#### backupStorageProvider
+
 | Key | Type | Default | Meaning |
 | --- | --- | --- | --- |
 | `region` | string | Required Field | *Example*: "us-east-1"<br><br>See [AWS documentation][3] for the full list. |
-| `availabilityZone` | string | Required Field | *Example*: "us-east-1a"<br><br>See [AWS documentation][4] for details. |
 | `disableSSL` | bool | `false` | Set this to `true` if you are using Minio (or another local, S3-compatible storage service) and your deployment is not secured. |
 | `s3ForcePathStyle` | bool | `false` | Set this to `true` if you are using a local storage service like Minio. |
 | `s3Url` | string | Required field for non-AWS-hosted storage| *Example*: http://minio:9000<br><br>You can specify the AWS S3 URL here for explicitness, but Ark can already generate it from `region`, `availabilityZone`, and `bucket`. This field is primarily for local sotrage services like Minio.|
```
Comment (abiogenesis-now) [inline docs/config-definition.md]: mind fixing my typo? s/sotrage/storage
thanks!

File: examples/azure/10-ark-config.yaml [hunk 7]
```diff
@@ -24,9 +24,7 @@ persistentVolumeProvider:
     apiTimeout: <YOUR_TIMEOUT>
 backupStorageProvider:
   bucket: <YOUR_BUCKET>
-  azure:
-    location: <YOUR_LOCATION>
-    apiTimeout: <YOUR_TIMEOUT>
```
Comment (abiogenesis-now) [inline examples/azure/10-ark-config.yaml]: do we not use the Azure API for object storage? or is it faster/doesn't require `apiTimeout` toggling?

File: docs/config-definition.md [hunk 8]
```diff
@@ -63,22 +58,44 @@ The configurable parameters are as follows:
...
 | `kmsKeyID` | string | Empty | *Example*: "502b409c-4da1-419f-a16e-eif453b3i49f"<br><br>Specify an [AWS KMS key][12] id to enable encryption of the backups stored in S3. Only works with AWS S3 and may require explicitly granting key usage rights.|
 
+#### persistentVolumeProvider
```
Comment (abiogenesis-now) [inline docs/config-definition.md]: Specify (AWS Only)? To be clearer that Minio is not supported

File: docs/config-definition.md (hunk 5 above)
Comment (abiogenesis-now) [inline docs/config-definition.md]: 👍

File: docs/config-definition.md [hunk 9]
```diff
@@ -50,7 +45,7 @@ The configurable parameters are as follows:
 
 | Key | Type | Default | Meaning |
 | --- | --- | --- | --- |
-| `persistentVolumeProvider` | CloudProviderConfig<br><br>(Supported key values are `aws`, `gcp`, and `azure`, but only one can be present. See the corresponding [AWS][0], [GCP][1], and [Azure][2]-specific configs.) | Required Field | The specification for whichever cloud provider the cluster is using for persistent volumes (to be snapshotted).<br><br> *NOTE*: For Azure, your Kubernetes cluster needs to be version 1.7.2+ in order to support PV snapshotting of its managed disks. |
+| `persistentVolumeProvider` | CloudProviderConfig<br><br>(Supported key values are `aws`, `gcp`, and `azure`, but only one can be present. See the corresponding [AWS][0], [GCP][1], and [Azure][2]-specific configs.) | None (Optional) | The specification for whichever cloud provider the cluster is using for persistent volumes (to be snapshotted), if any.<br><br>If not specified, Backups and Restores requesting PV snapshots & restores, respectively, are considered invalid. <br><br> *NOTE*: For Azure, your Kubernetes cluster needs to be version 1.7.2+ in order to support PV snapshotting of its managed disks. |
```
Comment (abiogenesis-now) [inline docs/config-definition.md]: Have we tested this in conjunction with the other PR https://github.com/heptio/ark/pull/45 that sets `--snapshot-volumes` and `--restore-volumes` to default true?

The author of that PR said it was fine to leave the quickstart commands without `--snapshot-volumes=false` since the basic Nginx example doesn't have PVs. I'm wondering if we actually do need to specify this flag now in the sample commands, since it looks it will error without a `peristentVolumeProvider` section specified. It's not a big deal, but if that's the case, we'll need to make sure to change the backup/restore commands in one of these two PRs. @ncdc does that seem right?

Comment (ncdc) [inline docs/config-definition.md]: @skriss is the primary motivation for making PVProvider optional to support running non-cloud (i.e. minio)?

I do think @abiogenesis-now brings up a good point. As far as UX goes, I think having a backup/restore fail validation because you forgot to set `--snapshot-volumes=false` might get annoying after a while, if the server isn't configured appropriately. I guess we might need to decide how likely running without a PV provider is. Also need to decide if we need to distinguish between something like "minio and legitimately no PV provider" and "aws/gcp/azure and I forgot to configure the PV provider, so it should be a validation error". Let's continue to discuss...

Comment (skriss) [inline docs/config-definition.md]: Hmm, yeah that is not a great UX now that true is becoming the default. We could just default to true if the PVProvider is configured, false otherwise. 

Minio is one use case; I also had in mind clusters not running in the cloud that users still want to back up to S3 (for example). This is supported but currently requires specifying a bogus PVProvider config.

File: examples/azure/10-ark-config.yaml (hunk 7 above)
Comment (skriss) [inline examples/azure/10-ark-config.yaml]: The slow API call issue is only with snapshot operations -- I wasn't actually using the timeout value for object storage API calls before anyway. I could keep it and switch to actually using it in the code, but I don't think it's necessary.

File: docs/config-definition.md (hunk 9 above)
Comment (ncdc) [inline docs/config-definition.md]: > We could just default to true if the PVProvider is configured, false otherwise.

I'm liking this. If you try to take a backup and the PVProvider wasn't configured, all you get is a backup but no snapshots.

However, if a backup does have snapshots, and then Ark was reconfigured for whatever reason with no PVProvider, maybe the restore should fail validation ("backup has volume snapshots but no PRProvider configured; please contact your Ark administrator to enable the PRProvider etc etc etc")?

Comment (skriss) [inline docs/config-definition.md]: The only thing I don't like about this is that there's no way around it - a user can't "override" the error.

Comment (ncdc) [inline docs/config-definition.md]: You can override if you set restore snapshots to false?

Comment (skriss) [inline docs/config-definition.md]: isn't that kind of the same problem we're trying to avoid re: UX (having to remember to specify that)? I was assuming we'd also default the flag to false for restores when no PVProvider.

File: docs/config-definition.md (hunk 6 above)
Comment (skriss) [inline docs/config-definition.md]: fixed.

File: docs/config-definition.md (hunk 8 above)
Comment (skriss) [inline docs/config-definition.md]: fixed.

File: examples/azure/10-ark-config.yaml (hunk 7 above)
Comment (abiogenesis-now) [inline examples/azure/10-ark-config.yaml]: ah ok, I think it's fine to leave it out then!

File: docs/config-definition.md (hunk 9 above)
Comment (skriss) [inline docs/config-definition.md]: I'm thinking that maybe what we should do is if you're restoring a backup that has snapshots linked, and --restore-volumes=false (either because you set it or because you don't have a PV provider so we default it to false), that we put a warning in the restore operation. I'll run it by joe.

Comment (ncdc) [inline docs/config-definition.md]: Like a prompt to the user where they have to indicate if they wish to proceed? And suppressible via `--ignore-warnings` or `--force` or something like that?

Comment (skriss) [inline docs/config-definition.md]: talked to Joe - he recommends we make --snapshot and --restore default to "auto", which means do the sensible thing based on presence of PVProvider and/or snapshots in the backup. Explicitly setting to yes can then cause validation errors if there's no PVProvider. In the case where there are snapshots in the backup but no PVProvider for restore, we should put a warning in the Restore.

**Comment by ncdc** [comment]
@skriss is this ready to go?

**Comment by skriss** [comment]
Not quite - I switched to the 3-way flag and need to do some more testing after that change.

**Comment by skriss** [comment]
@ncdc this is ready for another review. Main changes since the last time you looked:

* --snapshot-volumes and --restore-volumes have become nullable bool flags, where null means "auto" (default), which means to do the logical thing based on existence of PV Provider config
* add warning to the restore if the backup has snapshots but there's no PV Provider to restore them
* consolidate unstructured PV manipulation into `util/kube`

File: pkg/cmd/cli/backup/create.go [hunk 10]
```diff
@@ -70,19 +70,29 @@ func NewCreateOptions() *CreateOptions {
...
 	flags.DurationVar(&o.TTL, "ttl", o.TTL, "how long before the backup can be garbage collected")
-	flags.BoolVar(&o.SnapshotVolumes, "snapshot-volumes", o.SnapshotVolumes, "take snapshots of PersistentVolumes as part of the backup")
 	flags.Var(&o.IncludeNamespaces, "include-namespaces", "namespaces to include in the backup (use '*' for all namespaces)")
 	flags.Var(&o.ExcludeNamespaces, "exclude-namespaces", "namespaces to exclude from the backup")
 	flags.Var(&o.IncludeResources, "include-resources", "resources to include in the backup, formatted as resource.group, such as storageclasses.storage.k8s.io (use '*' for all resources)")
 	flags.Var(&o.ExcludeResources, "exclude-resources", "resources to exclude from the backup, formatted as resource.group, such as storageclasses.storage.k8s.io")
 	flags.Var(&o.Labels, "labels", "labels to apply to the backup")
 	flags.VarP(&o.Selector, "selector", "l", "only back up resources matching this label selector")
+
+	// we have to construct this directly because we want to specify a NoOptDefVal to maintain
```
Comment (ncdc) [inline pkg/cmd/cli/backup/create.go]: Why not let the default be nil?

File: pkg/cmd/server/server.go [hunk 11]
```diff
@@ -242,112 +239,108 @@ func (s *server) watchConfig(config *api.Config) {
...
 	}
-	s.backupService = cloudprovider.NewBackupService(cloud.ObjectStorage())
+
+	s.backupService = cloudprovider.NewBackupService(objectStorage)
 	return nil
 }
 
 func (s *server) initSnapshotService(config *api.Config) error {
+	if config.PersistentVolumeProvider == nil {
+		glog.Infof("PersistentVolumeProvider config not provided, skipping SnapshotService creation")
```
Comment (ncdc) [inline pkg/cmd/server/server.go]: Instead of saying "skipping SnapshotService creation", I would say "volume snapshots and restores are disabled"?

File: pkg/restore/restorers/pv_restorer.go [hunk 12]
```diff
@@ -43,31 +44,79 @@ func (sr *persistentVolumeRestorer) Handles(obj runtime.Unstructured, restore *a
...
+		if err := kubeutil.SetVolumeID(spec, volumeID); err != nil {
+			return nil, nil, err
 		}
 	}
 
-	return obj, nil
+	var warning error
+
+	if sr.snapshotService == nil && len(backup.Status.VolumeBackups) > 0 {
+		warning = fmt.Errorf("Restore %s/%s: backup %s/%s has PV snapshots but Ark server is not configured with a PersistentVolumeProvider so cannot restore thenm", restore.Namespace, restore.Name, backup.Namespace, backup.Name)
```
Comment (ncdc) [inline pkg/restore/restorers/pv_restorer.go]: Don't need to include the restore's or backup's namespace/name.

`"unable to restore PV snapshots: Ark server is not configured with a PersistentVolumeProvider"`
