### PR TITLE
Filter on resources that support get & delete

### LINKED ISSUE #475: backup all namespaces fails on origin 3.7
final log message in the backup logs is :

time="2018-05-05T09:15:39Z" level=info msg="Backup completed with errors: no Items field in &v1.Status{TypeMeta:v1.TypeMeta{Kind:\"Status\", APIVersion:\"v1\"}, ListMeta:v1.ListMeta{SelfLink:\"\", ResourceVersion:\"\", Continue:\"\"}, Status:\"Success\", Message:\"\", Reason:\"\", Details:(*v1.StatusDetails)(nil), Code:0}" backup=heptio-ark/all logSource="pkg/backup/backup.go:271"

#oc version
oc v3.7.0+7ed6862
kubernetes v1.7.6+a08f5eeb62
features: Basic-Auth GSSAPI Kerberos SPNEGO

Server ******************
openshift v3.7.0+7ed6862
kubernetes v1.7.6+a08f5eeb62

#ark version
Version: v0.8.1
Git commit: v0.8.1
Git tree state: clean

backing up a single namespace worked just fine.

### PR DESCRIPTION
**Pull request by nrb**
Some resources use GET for listing, which resulted in errors.

Fixes #475 

Signed-off-by: Nolan Brubaker <nolan@heptio.com>

### CODE REVIEW

File: pkg/discovery/helper.go [hunk 1]
```diff
@@ -109,7 +109,7 @@ func (h *helper) Refresh() error {
 
 	h.resources = discovery.FilteredBy(
 		discovery.ResourcePredicateFunc(func(groupVersion string, r *metav1.APIResource) bool {
```
Comment (ncdc) [inline pkg/discovery/helper.go]: @nrb if you wanted to, you could extract this into a separate function, and then unit test it by providing different `APIResource`s and ensuring that it returns true if and only if the resource supports all 4 verbs.

Comment (nrb) [reply pkg/discovery/helper.go]: That would make me a bit more confident in the change. I'll look into this.

File: pkg/discovery/helper_test.go [hunk 2]
```diff
@@ -84,3 +84,44 @@ func TestSortResources(t *testing.T) {
...
+
+func TestFilteringByVerbs(t *testing.T) {
+	tests := []struct {
+		name         string
+		groupVersion string
+		res          *metav1.APIResource
+		expected     bool
+	}{
+		{
+			name:         "resource that supports list, create, get, delete",
```
Comment (ncdc) [inline pkg/discovery/helper_test.go]: Can you do 1 more that has this same set of 4 but in a different order? Also please have at least 1 test where there are additional Verbs such as update, patch, and deletecollection.

**Comment by ncdc** [comment]
LGTM
