### PR TITLE
ignore terminating resources while doing a backup

### LINKED ISSUE #524: Ark should ignore Terminating resources
Currently, Ark tries to backup terminating resources, which often leads to failed backups. this might happen often when you have volatile workloads.

### PR DESCRIPTION
**Pull request by yastij**
this PR fixes #524

### CODE REVIEW

File: pkg/backup/item_backupper.go [hunk 1]
```diff
@@ -147,6 +147,22 @@ func (ib *defaultItemBackupper) backupItem(logger logrus.FieldLogger, obj runtim
 		return nil
 	}
 
+	resource := obj.UnstructuredContent()
+	if conditions, err := collections.GetSlice(resource, "status.conditions"); err != nil {
```
Comment (ncdc) [inline pkg/backup/item_backupper.go]: I think checking for `metadata.deletionTimestamp != nil` would be more universal - WDYT?

Comment (yastij) [reply pkg/backup/item_backupper.go]: yes it'll be easier.

**Comment by yastij** [comment]
@ncdc - updated

File: pkg/backup/item_backupper.go [hunk 2]
```diff
@@ -147,6 +147,12 @@ func (ib *defaultItemBackupper) backupItem(logger logrus.FieldLogger, obj runtim
 		return nil
 	}
 
+	resource := obj.UnstructuredContent()
+	if deletionTimestamp, err := collections.GetString(resource, "metadata.deletionTimestamp"); err == nil {
```
Comment (ncdc) [inline pkg/backup/item_backupper.go]: You can use `metadata.GetDeletionTimestamp()`

File: pkg/backup/item_backupper_test.go [hunk 3]
```diff
@@ -123,6 +123,35 @@ func TestBackupItemSkipsClusterScopedResourceWhenIncludeClusterResourcesFalse(t
 	assert.NoError(t, err)
 }
 
+func TestBackupItemWhenInTerminatingStatus(t *testing.T) {
+	f := true
+	ib := &defaultItemBackupper{
+		backup: &v1.Backup{
```
Comment (ncdc) [inline pkg/backup/item_backupper_test.go]: You should be able to do `&v1.Backup{}` - any reason you needed `IncludeClusterResources`?

File: pkg/backup/item_backupper_test.go [hunk 4]
```diff
@@ -123,6 +123,35 @@ func TestBackupItemSkipsClusterScopedResourceWhenIncludeClusterResourcesFalse(t
...
+			Spec: v1.BackupSpec{
+				IncludeClusterResources: &f,
```
Comment (ncdc) [inline pkg/backup/item_backupper_test.go]: If you do need to keep this, use `boolptr.True()`

File: pkg/backup/item_backupper_test.go [hunk 5]
```diff
@@ -123,6 +123,35 @@ func TestBackupItemSkipsClusterScopedResourceWhenIncludeClusterResourcesFalse(t
...
+			},
+		},
+		namespaces: collections.NewIncludesExcludes(),
+		resources:  collections.NewIncludesExcludes(),
+	}
+
+	u := unstructuredOrDie(`{"apiVersion":"v1","kind":"Foo","metadata":{"name":"bar", "namespace": "test", "deletionTimestamp": "timestamp"},  "status": {
```
Comment (ncdc) [inline pkg/backup/item_backupper_test.go]: Please use a real `deletionTimestamp`. You can probably remove the `conditions` too.

File: pkg/backup/item_backupper_test.go [hunk 6]
```diff
@@ -123,6 +123,35 @@ func TestBackupItemSkipsClusterScopedResourceWhenIncludeClusterResourcesFalse(t
 	assert.NoError(t, err)
 }
 
+func TestBackupItemWhenInTerminatingStatus(t *testing.T) {
```
Comment (ncdc) [inline pkg/backup/item_backupper_test.go]: Please put this in `TestBackupItemSkips`

Comment (yastij) [reply pkg/backup/item_backupper_test.go]: Done.

File: pkg/backup/item_backupper_test.go (hunk 5 above)
Comment (yastij) [reply pkg/backup/item_backupper_test.go]: Done.

File: pkg/backup/item_backupper.go (hunk 2 above)
Comment (yastij) [reply pkg/backup/item_backupper.go]: Done.

File: pkg/backup/item_backupper.go [hunk 7]
```diff
@@ -147,6 +147,9 @@ func (ib *defaultItemBackupper) backupItem(logger logrus.FieldLogger, obj runtim
 		return nil
 	}
 
+	if metadata.GetDeletionTimestamp() != nil {
+		return nil
```
Comment (ncdc) [inline pkg/backup/item_backupper.go]: Let's `log.Info` that we're skipping it because it's being deleted.

File: pkg/backup/item_backupper_test.go [hunk 8]
```diff
@@ -99,7 +109,12 @@ func TestBackupItemSkips(t *testing.T) {
 				backedUpItems: test.backedUpItems,
 			}
 
-			u := unstructuredOrDie(fmt.Sprintf(`{"apiVersion":"v1","kind":"Pod","metadata":{"namespace":"%s","name":"%s"}}`, test.namespace, test.name))
+			var deletionTimestamp string
```
Comment (ncdc) [inline pkg/backup/item_backupper_test.go]: Maybe we should use an actual `Pod` and then the unstructured converter so we're not conditionally modifying json...

File: pkg/backup/item_backupper.go (hunk 7 above)
Comment (yastij) [reply pkg/backup/item_backupper.go]: Done.

File: pkg/backup/item_backupper_test.go [hunk 9]
```diff
@@ -89,17 +91,37 @@ func TestBackupItemSkips(t *testing.T) {
...
-			u := arktest.UnstructuredOrDie(fmt.Sprintf(`{"apiVersion":"v1","kind":"Pod","metadata":{"namespace":"%s","name":"%s"}}`, test.namespace, test.name))
+			pod := &corev1api.Pod{
+				TypeMeta:   metav1.TypeMeta{APIVersion: "v1", Kind: "Pod"},
+				ObjectMeta: metav1.ObjectMeta{Namespace: test.namespace, Name: test.name},
+			}
+
+			if test.terminating {
+				pod.ObjectMeta.DeletionTimestamp = &metav1.Time{Time: time.Now()}
+			}
+			unstructuredObj, _ := runtime.DefaultUnstructuredConverter.ToUnstructured(pod)
```
Comment (ncdc) [inline pkg/backup/item_backupper_test.go]: Can you `require.NoError` on the returned error?

**Comment by yastij** [comment]
@ncdc - ready to merge

**Comment by ncdc** [comment]
LGTM, thanks @yastij!
