### PR TITLE
Run post-hooks even if backup actions fail

### LINKED ISSUE #511: Post hooks should always fire regardless of item action failures
Scenario:
1. pre-hook calls fsfreeze
1. some item action fails
1. return error immediately

This leaves the pod in an unusable state, since the file system is frozen.

### PR DESCRIPTION
**Pull request by carlpett**
Fixes #511 

This pulls all the action execution out into a new function (should there be matching changes in unit tests for this?), then ensures post-action hooks are run regardless of errors in the actions, and then returns any errors (including any in the post hook)

### CODE REVIEW

**Comment by ncdc** [comment]
Thanks @carlpett! For the time being, I think it's ok to leave the unit tests as they're currently structured. We may split `backupItem()` into multiple helper functions and then unit test them individually, as I wrote about [here](https://medium.com/@andy.goldstein/a-crazy-approach-to-unit-testing-in-go-3b7160bf9199), but we haven't decided on that just yet.

File: pkg/backup/item_backupper.go [hunk 1]
```diff
@@ -165,6 +166,64 @@ func (ib *defaultItemBackupper) backupItem(logger logrus.FieldLogger, obj runtim
 		return err
 	}
 
+	backupErrs := make([]error, 0)
+	err = ib.executeActions(log, obj, groupResource, name, namespace, metadata)
+	if err != nil {
+		log.WithError(err).Error("Error executing backup actions")
```
Comment (ncdc) [inline pkg/backup/item_backupper.go]: I'd change "backup" to "item"

**Comment by carlpett** [comment]
>This was mostly a cut & paste, right?
Yes.

File: pkg/backup/item_backupper.go (hunk 1 above)
Comment (carlpett) [reply pkg/backup/item_backupper.go]: Fixed!

**Comment by ncdc** [comment]
LGTM
